apiVersion: v1
kind: Service
metadata:
  name: song-service
  labels:
    app: song-service
spec:
  type: ClusterIP
  selector:
    app: song-service
  ports:
    - protocol: TCP
      # Port exposed by the service
      port: 80
      # The port exposed by the Pods targeted by the Service
      targetPort: 8081